name: CMake-Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: ls -la

      - name: Configure CMake
        run: mkdir build && cd build && cmake ..

      - name: Build
        run: cmake --build .

      - name: Upload build artifacts for tests
        env:
          TESTS_DIR: ${{github.workspace}}/cmake-build-release/
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-for-tests
          path: ${{env.TESTS_DIR}}/
          
  Tests:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Download artifacts for tests
        uses: actions/download-artifact@v2
        with:
          name: artifacts-for-tests

      - name: Run tests
        run: |
          echo "Running unit tests ..."
          echo "unit tests done!"
